---

sudo: false

language: bds

before_install:

  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-2.0.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH

install:

  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda

  # RNAsik should pull bds with it
  #- conda install --yes --channel serine bigdatascript
  # For now doing specific bds version install, waiting on next release
  - conda install --yes --channel serine/label/dev bigdatascript=v2.0+9ad04607
  - conda install --yes --channel serine rnasik

script:

  - ./test/get_geneids.bash
  - ./test/sik_test.bash
  # two different test, one for conda install
  # does RNAsik from conda install works?
  # going to comment this one out while waiting on next bds release
  #- RNAsik --help
  # does RNAsik from master branch works?
  #- ./bin/RNAsik --help
  # some inconsistency with exit value
  - ./bin/RNAsik
