{% set version = "1.5.4.1" %}

package:
  name: rnasik
  version: {{ version }}

source:
  fn: rnasik.tar.gz
  url: https://codeload.github.com/MonashBioinformaticsPlatform/RNAsik-pipe/tar.gz/refs/tags/1.5.4.1
  sha256: 37d489d61511414886d62618e33e9828318301164531a18fe9dd052f326bb6bb

build:
  number: 0
  skip: False

requirements:
  run:
    - bigdatascript=v2.0rc10  # serine/bigdatascript
    - openjdk=11.0.8
    - python=3.6.7
    - star=2.7.2b
    - bwa=0.7.17
    - hisat2=2.2.1
    - bedtools=2.25.0
    - picard=2.18.9
    - samtools=1.9
    - subread=1.6.2
    - qualimap=2.2.2d
    - htslib=1.9
    - fastqc=0.11.7
    - multiqc=1.10.1

test:
  commands:
    - "RNAsik 2>&1 | grep 'RNAsik version'"

about:
  home: "https://monashbioinformaticsplatform.github.io/RNAsik-pipe/"
  license: Apache 2.0
  summary: "Another RNAseq pipeline."
